name: solve_tutor
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # nb_utils: ^5.0.8
  intl: ^0.18.1
  google_fonts: ^4.0.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.3
  firebase_analytics: ^10.4.3
  cloud_firestore: ^4.7.1
  image_picker: ^0.8.3+2
  firebase_storage: ^11.2.1
  uuid: ^3.0.4
  google_sign_in: ^6.1.2
  flutter_keyboard_visibility: ^5.4.1
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  fluttertoast: ^8.2.2

  photo_view: 0.14.0
  cached_network_image: ^3.2.3
  gallery_saver: ^2.3.2
  emoji_picker_flutter: ^1.6.0
  table_calendar: ^3.0.9
  flutter_local_notifications: ^13.0.0
  number_paginator: ^0.2.3

  logging: ^1.2.0
  file_picker: ^5.3.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  dotted_border: ^2.0.0+3
  flutter_reorderable_list: ^1.3.1
  video_thumbnail: ^0.5.3
  flutter_reorderable_grid_view: ^4.0.0
  responsive_framework: ^1.0.0
  videosdk: ^1.1.3

  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansThai-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansThai-Bold.ttf
          weight: 700
    - family: NotoSansMed
      fonts:
        - asset: assets/fonts/NotoSansThai-Medium.ttf
    - family: NotoSansBold
      fonts:
        - asset: assets/fonts/NotoSansThai-Bold.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
