// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuzjhNPBaB7jlldGH_kC8GDqrKKliQU8Q',
    appId: '1:770917809768:android:4d4f53c1fca32b8757c5dd',
    messagingSenderId: '770917809768',
    projectId: 'solve-f1778',
    storageBucket: 'solve-f1778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-XXFVKvmeEesO-iFSbdzrRjwKechPGVE',
    appId: '1:770917809768:ios:fc19743fbbe06e3957c5dd',
    messagingSenderId: '770917809768',
    projectId: 'solve-f1778',
    storageBucket: 'solve-f1778.appspot.com',
    androidClientId: '770917809768-0sto7cd1grdv8m9fcbj177q0tiblvd1h.apps.googleusercontent.com',
    iosClientId: '770917809768-8b1h93hjq8d7gf5ln1ds6qcavm72fq2n.apps.googleusercontent.com',
    iosBundleId: 'com.solve.tutor',
  );

}